version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      FLASK_ENV: production
      PORT: 4000
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped
    command: sh -c "python run_migrations.py && gunicorn -w 4 -b 0.0.0.0:4000 wsgi:app"
